from environs import Env

env = Env()
env.read_env()

SMS_ACTIVATE_API_KEY = env.str('SMS_ACTIVATE_API_KEY')

HAPPN_URL = env.str('HAPPN_URL')

CODES = {
    "0": "RU",
    "1": "UA",
    "2": "KZ",
    "3": "CN",
    "4": "PH",
    "5": "MM",
    "6": "ID",
    "7": "MY",
    "8": "KE",
    "9": "TZ",
    "10": "VN",
    "11": "KG",
    "12": "USA",
    "13": "IL",
    "14": "HK",
    "15": "PL",
    "16": "UK",
    "17": "MG",
    "18": "DC",
    "19": "NG",
    "20": "MO",
    "21": "EG",
    "22": "IO",
    "23": "IE",
    "24": "KH",
    "25": "LA",
    "26": "HT",
    "27": "IV",
    "28": "GM",
    "29": "CS",
    "30": "YE",
    "31": "ZA",
    "32": "RO",
    "33": "CO",
    "34": "EE",
    "35": "AZ",
    "36": "CA",
    "37": "MA",
    "38": "GH",
    "39": "AR",
    "40": "UZ",
    "41": "CM",
    "42": "TD",
    "43": "DE",
    "44": "LT",
    "45": "HR",
    "46": "SE",
    "47": "IQ",
    "48": "NL",
    "49": "LV",
    "50": "AT",
    "51": "BY",
    "52": "TH",
    "53": "SA",
    "54": "MX",
    "55": "TW",
    "56": "ES",
    "57": "IR",
    "58": "DZ",
    "59": "SI",
    "60": "BD",
    "61": "SN",
    "62": "TR",
    "63": "CZ",
    "64": "SR",
    "65": "PE",
    "66": "PK",
    "67": "NZ",
    "68": "GQ",
    "69": "ML",
    "70": "VE",
    "71": "ET",
    "72": "MN",
    "73": "BR",
    "74": "AF",
    "75": "UG",
    "76": "AO",
    "77": "CY",
    "78": "FR",
    "79": "PG",
    "80": "MZ",
    "81": "NP",
    "82": "BE",
    "83": "BG",
    "84": "HU",
    "85": "MD",
    "86": "IT",
    "87": "PY",
    "88": "HN",
    "89": "TN",
    "90": "NI",
    "91": "TL",
    "92": "BO",
    "93": "CR",
    "94": "GT",
    "95": "AE",
    "96": "ZW",
    "97": "PR",
    "98": "SD",
    "99": "TG",
    "100": "KW",
    "101": "SV",
    "102": "LY",
    "103": "JM",
    "104": "TT",
    "105": "EC",
    "106": "SZ",
    "107": "OM",
    "108": "BA",
    "109": "DO",
    "110": "SY",
    "111": "QA",
    "112": "PA",
    "113": "CU",
    "114": "MR",
    "115": "SL",
    "116": "JO",
    "117": "PT",
    "118": "BB",
    "119": "BI",
    "120": "BJ",
    "121": "BN",
    "122": "BS",
    "123": "BW",
    "124": "BZ",
    "125": "CF",
    "126": "DM",
    "127": "GD",
    "128": "GE",
    "129": "GR",
    "130": "GW",
    "131": "GY",
    "132": "IS",
    "133": "KM",
    "134": "SA",
    "135": "LR",
    "136": "LS",
    "137": "MW",
    "138": "NA",
    "139": "NE",
    "140": "RW",
    "141": "SK",
    "142": "SR",
    "143": "TJ",
    "144": "MC",
    "145": "BH",
    "146": "RE",
    "147": "ZM",
    "148": "AM",
    "149": "SO",
    "150": "CG",
    "151": "CL",
    "152": "BU",
    "153": "LB",
    "154": "GA",
    "155": "AL",
    "156": "UY",
    "157": "MU",
    "158": "BT",
    "159": "MV",
    "160": "GP",
    "161": "TM",
    "162": "FR",
    "163": "FI",
    "164": "GF",
    "165": "LU",
    "166": "VC",
    "167": "EC",
    "168": "DJ",
    "169": "AG",
    "170": "KY",
    "171": "CS",
    "172": "DK",
    "173": "CH",
    "174": "NO",
    "175": "AU",
    "176": "ER",
    "177": "SS",
    "178": "ST",
    "179": "AW",
    "180": "MS",
    "181": "AI",
    "183": "MK",
    "184": "SC",
    "185": "NC",
    "186": "CV",
    "187": "USA",
    "189": "FJ",
    "196": "SG",
    "201": "GI"
}

COUNTRIES = {
    "0": "Russia",
    "1": "Ukraine",
    "2": "Kazakhstan",
    "3": "China",
    "4": "Philippines",
    "5": "Myanmar",
    "6": "Indonesia",
    "7": "Malaysia",
    "8": "Kenya",
    "9": "Tanzania",
    "10": "Vietnam",
    "11": "Kyrgyzstan",
    "12": "USA (virtual)",
    "13": "Israel",
    "14": "HongKong",
    "15": "Poland",
    "16": "England",
    "17": "Madagascar",
    "18": "DCongo",
    "19": "Nigeria",
    "20": "Macao",
    "21": "Egypt",
    "22": "India",
    "23": "Ireland",
    "24": "Cambodia",
    "25": "Laos",
    "26": "Haiti",
    "27": "Ivory",
    "28": "Gambia",
    "29": "Serbia",
    "30": "Yemen",
    "31": "Southafrica",
    "32": "Romania",
    "33": "Colombia",
    "34": "Estonia",
    "35": "Azerbaijan",
    "36": "Canada",
    "37": "Morocco",
    "38": "Ghana",
    "39": "Argentina",
    "40": "Uzbekistan",
    "41": "Cameroon",
    "42": "Chad",
    "43": "Germany",
    "44": "Lithuania",
    "45": "Croatia",
    "46": "Sweden",
    "47": "Iraq",
    "48": "Netherlands",
    "49": "Latvia",
    "50": "Austria",
    "51": "Belarus",
    "52": "Thailand",
    "53": "Saudiarabia",
    "54": "Mexico",
    "55": "Taiwan",
    "56": "Spain",
    "57": "Iran",
    "58": "Algeria",
    "59": "Slovenia",
    "60": "Bangladesh",
    "61": "Senegal",
    "62": "Turkey",
    "63": "Czech",
    "64": "Srilanka",
    "65": "Peru",
    "66": "Pakistan",
    "67": "Newzealand",
    "68": "Guinea",
    "69": "Mali",
    "70": "Venezuela",
    "71": "Ethiopia",
    "72": "Mongolia",
    "73": "Brazil",
    "74": "Afghanistan",
    "75": "Uganda",
    "76": "Angola",
    "77": "Cyprus",
    "78": "France",
    "79": "Papua",
    "80": "Mozambique",
    "81": "Nepal",
    "82": "Belgium",
    "83": "Bulgaria",
    "84": "Hungary",
    "85": "Moldova",
    "86": "Italy",
    "87": "Paraguay",
    "88": "Honduras",
    "89": "Tunisia",
    "90": "Nicaragua",
    "91": "Timorleste",
    "92": "Bolivia",
    "93": "Costarica",
    "94": "Guatemala",
    "95": "Uae",
    "96": "Zimbabwe",
    "97": "Puertorico",
    "98": "Sudan",
    "99": "Togo",
    "100": "Kuwait",
    "101": "Salvador",
    "102": "Libyan",
    "103": "Jamaica",
    "104": "Trinidad",
    "105": "Ecuador",
    "106": "Swaziland",
    "107": "Oman",
    "108": "Bosnia",
    "109": "Dominican",
    "110": "Syrian",
    "111": "Qatar",
    "112": "Panama",
    "113": "Cuba",
    "114": "Mauritania",
    "115": "Sierraleone",
    "116": "Jordan",
    "117": "Portugal",
    "118": "Barbados",
    "119": "Burundi",
    "120": "Benin",
    "121": "Brunei",
    "122": "Bahamas",
    "123": "Botswana",
    "124": "Belize",
    "125": "Caf",
    "126": "Dominica",
    "127": "Grenada",
    "128": "Georgia",
    "129": "Greece",
    "130": "Guineabissau",
    "131": "Guyana",
    "132": "Iceland",
    "133": "Comoros",
    "134": "Saintkitts",
    "135": "Liberia",
    "136": "Lesotho",
    "137": "Malawi",
    "138": "Namibia",
    "139": "Niger",
    "140": "Rwanda",
    "141": "Slovakia",
    "142": "Suriname",
    "143": "Tajikistan",
    "144": "Monaco",
    "145": "Bahrain",
    "146": "Reunion",
    "147": "Zambia",
    "148": "Armenia",
    "149": "Somalia",
    "150": "Congo",
    "151": "Chile",
    "152": "Burkinafaso",
    "153": "Lebanon",
    "154": "Gabon",
    "155": "Albania",
    "156": "Uruguay",
    "157": "Mauritius",
    "158": "Bhutan",
    "159": "Maldives",
    "160": "Guadeloupe",
    "161": "Turkmenistan",
    "162": "Frenchguiana",
    "163": "Finland",
    "164": "Saintlucia",
    "165": "Luxembourg",
    "166": "Saintvincentgrenadines",
    "167": "Equatorialguinea",
    "168": "Djibouti",
    "169": "Antiguabarbuda",
    "170": "Caymanislands",
    "171": "Montenegro",
    "172": "Denmark",
    "173": "Switzerland",
    "174": "Norway",
    "175": "Australia",
    "176": "Eritrea",
    "177": "Southsudan",
    "178": "Saotomeandprincipe",
    "179": "Aruba",
    "180": "Montserrat",
    "181": "Anguilla",
    "183": "Northmacedonia",
    "184": "Seychelles",
    "185": "Newcaledonia",
    "186": "Capeverde",
    "187": "USA",
    "189": "Fiji",
    "196": "Singapore",
    "201": "Gibraltar"
}

COUNTRY_CODES = {
    "Afghanistan": "AF",
    "Aland Islands": "AX",
    "Albania": "AL",
    "Algeria": "DZ",
    "American Samoa": "AS",
    "AndorrA": "AD",
    "Angola": "AO",
    "Anguilla": "AI",
    "Antarctica": "AQ",
    "Antigua and Barbuda": "AG",
    "Argentina": "AR",
    "Armenia": "AM",
    "Aruba": "AW",
    "Australia": "AU",
    "Austria": "AT",
    "Azerbaijan": "AZ",
    "Bahamas": "BS",
    "Bahrain": "BH",
    "Bangladesh": "BD",
    "Barbados": "BB",
    "Belarus": "BY",
    "Belgium": "BE",
    "Belize": "BZ",
    "Benin": "BJ",
    "Bermuda": "BM",
    "Bhutan": "BT",
    "Bolivia": "BO",
    "Bosnia and Herzegovina": "BA",
    "Botswana": "BW",
    "Bouvet Island": "BV",
    "Brazil": "BR",
    "British Indian Ocean Territory": "IO",
    "Brunei Darussalam": "BN",
    "Bulgaria": "BG",
    "Burkina Faso": "BF",
    "Burundi": "BI",
    "Cambodia": "KH",
    "Cameroon": "CM",
    "Canada": "CA",
    "Cape Verde": "CV",
    "Cayman Islands": "KY",
    "Central African Republic": "CF",
    "Chad": "TD",
    "Chile": "CL",
    "China": "CN",
    "Christmas Island": "CX",
    "Cocos (Keeling) Islands": "CC",
    "Colombia": "CO",
    "Comoros": "KM",
    "Congo": "CG",
    "Congo, The Democratic Republic of the": "CD",
    "Cook Islands": "CK",
    "Costa Rica": "CR",
    "Cote D'Ivoire": "CI",
    "Croatia": "HR",
    "Cuba": "CU",
    "Cyprus": "CY",
    "Czech Republic": "CZ",
    "Denmark": "DK",
    "Djibouti": "DJ",
    "Dominica": "DM",
    "Dominican Republic": "DO",
    "Ecuador": "EC",
    "Egypt": "EG",
    "El Salvador": "SV",
    "Equatorial Guinea": "GQ",
    "Eritrea": "ER",
    "Estonia": "EE",
    "Ethiopia": "ET",
    "Falkland Islands (Malvinas)": "FK",
    "Faroe Islands": "FO",
    "Fiji": "FJ",
    "Finland": "FI",
    "France": "FR",
    "French Guiana": "GF",
    "French Polynesia": "PF",
    "French Southern Territories": "TF",
    "Gabon": "GA",
    "Gambia": "GM",
    "Georgia": "GE",
    "Germany": "DE",
    "Ghana": "GH",
    "Gibraltar": "GI",
    "Greece": "GR",
    "Greenland": "GL",
    "Grenada": "GD",
    "Guadeloupe": "GP",
    "Guam": "GU",
    "Guatemala": "GT",
    "Guernsey": "GG",
    "Guinea": "GN",
    "Guinea-Bissau": "GW",
    "Guyana": "GY",
    "Haiti": "HT",
    "Heard Island and Mcdonald Islands": "HM",
    "Holy See (Vatican City State)": "VA",
    "Honduras": "HN",
    "Hong Kong": "HK",
    "Hungary": "HU",
    "Iceland": "IS",
    "India": "IN",
    "Indonesia": "ID",
    "Iran, Islamic Republic Of": "IR",
    "Iraq": "IQ",
    "Ireland": "IE",
    "Isle of Man": "IM",
    "Israel": "IL",
    "Italy": "IT",
    "Jamaica": "JM",
    "Japan": "JP",
    "Jersey": "JE",
    "Jordan": "JO",
    "Kazakhstan": "KZ",
    "Kenya": "KE",
    "Kiribati": "KI",
    "Korea, Democratic People'S Republic of": "KP",
    "Korea, Republic of": "KR",
    "Kuwait": "KW",
    "Kyrgyzstan": "KG",
    "Lao People'S Democratic Republic": "LA",
    "Latvia": "LV",
    "Lebanon": "LB",
    "Lesotho": "LS",
    "Liberia": "LR",
    "Libyan Arab Jamahiriya": "LY",
    "Liechtenstein": "LI",
    "Lithuania": "LT",
    "Luxembourg": "LU",
    "Macao": "MO",
    "Macedonia, The Former Yugoslav Republic of": "MK",
    "Madagascar": "MG",
    "Malawi": "MW",
    "Malaysia": "MY",
    "Maldives": "MV",
    "Mali": "ML",
    "Malta": "MT",
    "Marshall Islands": "MH",
    "Martinique": "MQ",
    "Mauritania": "MR",
    "Mauritius": "MU",
    "Mayotte": "YT",
    "Mexico": "MX",
    "Micronesia, Federated States of": "FM",
    "Moldova, Republic of": "MD",
    "Monaco": "MC",
    "Mongolia": "MN",
    "Montserrat": "MS",
    "Morocco": "MA",
    "Mozambique": "MZ",
    "Myanmar": "MM",
    "Namibia": "NA",
    "Nauru": "NR",
    "Nepal": "NP",
    "Netherlands": "NL",
    "Netherlands Antilles": "AN",
    "New Caledonia": "NC",
    "New Zealand": "NZ",
    "Nicaragua": "NI",
    "Niger": "NE",
    "Nigeria": "NG",
    "Niue": "NU",
    "Norfolk Island": "NF",
    "Northern Mariana Islands": "MP",
    "Norway": "NO",
    "Oman": "OM",
    "Pakistan": "PK",
    "Palau": "PW",
    "Palestinian Territory, Occupied": "PS",
    "Panama": "PA",
    "Papua New Guinea": "PG",
    "Paraguay": "PY",
    "Peru": "PE",
    "Philippines": "PH",
    "Pitcairn": "PN",
    "Poland": "PL",
    "Portugal": "PT",
    "Puerto Rico": "PR",
    "Qatar": "QA",
    "Reunion": "RE",
    "Romania": "RO",
    "Russian Federation": "RU",
    "RWANDA": "RW",
    "Saint Helena": "SH",
    "Saint Kitts and Nevis": "KN",
    "Saint Lucia": "LC",
    "Saint Pierre and Miquelon": "PM",
    "Saint Vincent and the Grenadines": "VC",
    "Samoa": "WS",
    "San Marino": "SM",
    "Sao Tome and Principe": "ST",
    "Saudi Arabia": "SA",
    "Senegal": "SN",
    "Serbia and Montenegro": "CS",
    "Seychelles": "SC",
    "Sierra Leone": "SL",
    "Singapore": "SG",
    "Slovakia": "SK",
    "Slovenia": "SI",
    "Solomon Islands": "SB",
    "Somalia": "SO",
    "South Africa": "ZA",
    "South Georgia and the South Sandwich Islands": "GS",
    "Spain": "ES",
    "Sri Lanka": "LK",
    "Sudan": "SD",
    "Suriname": "SR",
    "Svalbard and Jan Mayen": "SJ",
    "Swaziland": "SZ",
    "Sweden": "SE",
    "Switzerland": "CH",
    "Syrian Arab Republic": "SY",
    "Taiwan, Province of China": "TW",
    "Tajikistan": "TJ",
    "Tanzania, United Republic of": "TZ",
    "Thailand": "TH",
    "Timor-Leste": "TL",
    "Togo": "TG",
    "Tokelau": "TK",
    "Tonga": "TO",
    "Trinidad and Tobago": "TT",
    "Tunisia": "TN",
    "Turkey": "TR",
    "Turkmenistan": "TM",
    "Turks and Caicos Islands": "TC",
    "Tuvalu": "TV",
    "Uganda": "UG",
    "Ukraine": "UA",
    "United Arab Emirates": "AE",
    "United Kingdom": "GB",
    "United States": "US",
    "United States Minor Outlying Islands": "UM",
    "Uruguay": "UY",
    "Uzbekistan": "UZ",
    "Vanuatu": "VU",
    "Venezuela": "VE",
    "Viet Nam": "VN",
    "Virgin Islands, British": "VG",
    "Virgin Islands, U.S.": "VI",
    "Wallis and Futuna": "WF",
    "Western Sahara": "EH",
    "Yemen": "YE",
    "Zambia": "ZM",
    "Zimbabwe": "ZW"
}
